# resume/.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "webide"

pages:
  image: debian
  timeout: 30 minutes
  interruptible: true
  script:
    - |
        set -euvx
        export
        apt-get --yes update
        apt-get --yes install \
            build-essential \
            texlive \
            texlive-base \
            texlive-full \
            texlive-latex-extra \
            texlive-latex-recommended \
            tree \
            ;
        make --always-make clean all public/index.html
  artifacts:
    paths:
      - public
